src/JourneyBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from JourneyBlog import settings
from django.conf.urls.static import static

from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")), #pour signup
    path("accounts/", include("django.contrib.auth.urls")), #pour login et logout
    path('posts/', include('posts.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/posts/urls.py
from django.urls import path
from posts.views import BlogHome, BlogPostCreate, BlogPostEdit, BlogPostDetail, BlogPostDelete, UserSearchView, SignUpView
from django.urls import path, include

# from django.views.generic.base import TemplateView

app_name = "posts"

urlpatterns = [
    path('create/', BlogPostCreate.as_view(), name="create"),
    path('search/', UserSearchView.as_view(), name="user_search"),
    path('<str:username>/', BlogHome.as_view(), name="profile"),
    path('<str:username>/<str:slug>/', BlogPostDetail.as_view(), name="post"),
    path('edit/<str:username>/<str:slug>/', BlogPostEdit.as_view(), name="edit"),
    path('delete/<str:username>/<str:slug>/', BlogPostDelete.as_view(), name="delete"),
]

src/posts/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.template.defaultfilters import slugify
from model_utils.models import TimeStampedModel

User = get_user_model()


class Pictures(TimeStampedModel):
    img = models.ImageField(upload_to='images')

    def __str__(self):
        return str(self.img)

class BlogPost(TimeStampedModel):
    title = models.CharField(max_length=255, unique=False, verbose_name="Where did you go ?")
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    last_updated = models.DateTimeField(auto_now=True)
    created_on = models.DateField(blank=True, null=True)
    published = models.BooleanField(default=False, verbose_name="Do you want to publish it ?")
    content = models.TextField(blank=True, verbose_name="Share your journey ")
    images = models.ManyToManyField(Pictures, blank=True, verbose_name="Add attachment")

    @property
    def author_or_default(self):
        return self.author.username if self.author else "L'auteur inconnu"

    # def get_absolute_url(self):
    #     return reverse("posts:home")

    class Meta:
        ordering = ['-created_on']
        verbose_name = "Article"


    def __str__(self):
      return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(f"{self.author.username}-{self.title}")
        super().save(*args, **kwargs)

src/posts/forms.py
from django import forms
from .models import Pictures
from django.forms import modelformset_factory

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


# Sign Up Form
class SignUpForm(UserCreationForm):
    # first_name = forms.CharField(max_length=30, required=False, help_text='Optional')
    # last_name = forms.CharField(max_length=30, required=False, help_text='Optional')
    email = forms.EmailField(max_length=254, help_text='Enter a valid email address')

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password1',
            'password2',
            ]

class MultipleFileInput(forms.FileInput):
    def render(self, name, value, attrs=None, renderer=None):
        if 'multiple' not in self.attrs:
            self.attrs['multiple'] = 'multiple'
        return super().render(name, value, attrs, renderer)

class PictureForm(forms.ModelForm):
    img = forms.FileField(widget=MultipleFileInput(), required=False, label='Add attachment ')

    class Meta:
        model = Pictures
        fields = ['img']

PictureFormSet = modelformset_factory(Pictures, form=PictureForm, extra=1)

src/posts/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from .forms import PictureFormSet
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.http import Http404

from django.views import View

from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from .forms import SignUpForm
from django.contrib.auth.models import User
from datetime import datetime


from posts.models import BlogPost, Pictures

User = get_user_model()


# Sign Up View
class SignUpView(CreateView):
    form_class = SignUpForm
    template_name = 'user/signup.html'

    def get_success_url(self):
        username = self.object.username
        return reverse('posts:profile', kwargs={'username': username})

class UserSearchView(View):
    def get(self, request, *args, **kwargs):
        username = request.GET.get('username')

        username = username.lower() if username else username

        # Si le nom d'utilisateur est vide ou non valide
        if not username or not self.is_valid_username(username):
            return redirect('home')

        return redirect('posts:profile', username=username.lower())

    def is_valid_username(self, username):
        return User.objects.filter(username=username).exists()

class BlogHome(ListView):
    model = BlogPost
    context_object_name = "posts"

    def get_queryset(self):
        # Obtenir le username depuis l'URL
        username = self.kwargs.get('username')
        # Obtenir le User object correspondant
        user = User.objects.get(username=username)

        try:
            # Obtenir le User object correspondant
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            raise Http404("User not found")

        # Filtrer les posts par cet utilisateur
        if self.request.user.is_authenticated and self.request.user.username == username:
            # Si l'utilisateur est authentifié et qu'il visite sa propre page, on lui montre tous ses posts
            return BlogPost.objects.filter(author=user)
        else:
            # Si un visiteur ou un autre utilisateur visite cette page, ne montrer que les posts publiés
            return BlogPost.objects.filter(author=user, published=True)

    def get_context_data(self, **kwargs):
        context = super(BlogHome, self).get_context_data(**kwargs)
        context['username_in_url'] = self.kwargs.get('username')
        return context

class BlogPostCreate(CreateView):
    model = BlogPost
    template_name = 'posts/blogpost_create.html'
    fields = ['title', 'content', 'published']

    def get_success_url(self):
        return reverse('posts:profile', kwargs={'username': self.request.user.username})

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data["pictures_formset"] = PictureFormSet(self.request.POST, self.request.FILES, prefix='pictures')
        else:
            data["pictures_formset"] = PictureFormSet(prefix='pictures')
        return data

    def form_valid(self, form):
        form.instance.author = self.request.user  # Assigner l'auteur
        form.instance.created_on = datetime.now()

        context = self.get_context_data()
        pictures_form = context["pictures_formset"][0]  # prendre le premier formulaire du formset
        self.object = form.save()

        if pictures_form.is_valid():
            for file in self.request.FILES.getlist('pictures-0-img'):
                picture = Pictures(img=file)
                picture.save()
                self.object.images.add(picture)

        return super().form_valid(form)

class BlogPostEdit(UpdateView):
    model = BlogPost
    template_name = 'posts/blogpost_edit.html'
    fields = ['title', 'content', 'published']

    def get_success_url(self):
        return reverse('posts:profile', kwargs={'username': self.request.user.username})

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data["pictures_formset"] = PictureFormSet(self.request.POST, self.request.FILES, prefix='pictures')
        else:
            data["pictures_formset"] = PictureFormSet(queryset=Pictures.objects.none(), prefix='pictures')
        return data

    def form_valid(self, form):
        form.instance.author = self.request.user  # Assigner l'auteur
        form.instance.updated_on = datetime.now()

        context = self.get_context_data()
        pictures_form = context["pictures_formset"]

        self.object = form.save()

        remove_all_images = self.request.POST.get('remove_all_images', '0') == '1'
        if remove_all_images:
            self.object.images.clear()

        if pictures_form.is_valid():
            pictures_form.instance = self.object
            pictures_form.save()

            # Supprimer les anciennes images

            for file in self.request.FILES.getlist('pictures-0-img'):
                picture = Pictures(img=file)
                picture.save()
                self.object.images.add(picture)

        return super().form_valid(form)

class BlogPostDetail(DetailView):
    model = BlogPost
    context_object_name = "post"



class BlogPostDelete(DeleteView):
    model = BlogPost
    success_url = reverse_lazy("posts:profile")
    def get_success_url(self):
        return reverse('posts:profile', kwargs={'username': self.request.user.username})

src/posts/templates/posts/blogpost_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

    <form method="POST">
        {% csrf_token %}
        <p>Êtes-vous sûr de vouloir supprimer "{{ object }}"?</p>

        <input type="submit" value="Oui, supprimer">
    </form>

{% endblock %}

src/posts/templates/posts/blogpost_create.html
{% extends 'blogpost_base.html' %}
{% load static %}

{% block head_extra %}
  <link rel="stylesheet" href="{% static 'css/blogpost_base.css' %}">
  <link rel="stylesheet" href="{% static 'css/blogpost_create.css' %}">
{% endblock %}

{% block title %}Create an article{% endblock %}

{% block content %}
    <div class="background-container">
      <img src="{% static 'images/coffee.jpg' %}" alt="Iceland Image">
    </div>

    <div class="container">
      <div class="add-form">

        <div class="title">Create a post</div>

        <form class="form" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
            <div class="title-label">
              {{ form.title.label_tag }}
            </div>
            <div class="title-input">
              {{ form.title }}
            </div>

            <div class="content-label">
            {{ form.content.label_tag }}
            </div>
            <div class="content-form">
            {{ form.content }}
            </div>

    <div class="published-picture-container">
      <div class="published">
        <p>
            {{ form.published.label_tag }}
            {{ form.published }}
        </p>
      </div>

      <div class="picture">
        <div class="picture-attachment-container">

          <div class="picture-attachment-label-container">
            <svg class="picture-attachment-label-icon" viewBox="0 0 24 24" fill="none" xmlns="https://www.w3.org/TR/SVG/"><path d="M21.438 11.662l-9.19 9.19a6.003 6.003 0 11-8.49-8.49l9.19-9.19a4.002 4.002 0 015.66 5.66l-9.2 9.19a2.001 2.001 0 11-2.83-2.83l8.49-8.48" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path></svg>

            {{ pictures_formset.management_form }}

        <!-- Afficher uniquement le premier formulaire du formset -->
            {{ pictures_formset.0.as_p }}
          </div>

          <div class="picture-attachment-wrapper hidden">
            <div class="picture-attachment">
              <img class="picture-attachment-image hidden" src="" alt="">
              <p class="picture-attachment-extension hidden"></p>
            </div>
          </div>
      </div>
    </div>
          <button class="add-btn" type="submit">Create</button>
        </form>

        <div class="go-back"><a href="{% url 'posts:profile' request.user.username %}">GO BACK</a></div>
      </div>
    </div>

    <script>

      document.addEventListener('DOMContentLoaded', function() {
        // Sélectionner l'élément <label> existant
        const labelElement = document.querySelector("label[for='id_pictures-0-img']");

        // Créer un nouvel élément <span> pour contenir le texte du label
        const labelSpan = document.createElement('span');
        labelSpan.id = 'attachmentLabel';
        labelSpan.textContent = 'Add attachment :';

        // Insérer le <span> dans le <label> pour l'ajout du nombre d'images
        labelElement.innerHTML = '';
        labelElement.appendChild(labelSpan);

        // Sélectionner l'élément <input type="file">
        const fileInput = document.getElementById('id_pictures-0-img');

        // Écouter l'événement 'change' sur l'input de fichier
        fileInput.addEventListener('change', function() {
          const numFiles = fileInput.files.length;
          if (numFiles === 1) {
            labelSpan.textContent = '1 file added';
          } else if (numFiles > 1) {
            labelSpan.textContent = `${numFiles} files added`;
          } else {
            labelSpan.textContent = 'Add attachment :';
          }
        });
      });

    </script>

{% endblock %}

src/posts/templates/posts/blogpost_detail.html
{% extends 'blogpost_base.html' %}
{% load static %}

{% block title %}
    <title>{{ post.title }}</title>
{% endblock %}

{% block head_extra %}
  {% comment %} <link rel="stylesheet" href="{% static 'css/blogpost_detail.css' %}"> {% endcomment %}
  <title>Journey Blog</title>

  <style>
    @import url('https://fonts.googleapis.com/css2?family=Pacifico&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Maven+Pro&display=swap');

    html, body {
      height: 100%;
      margin: 0;
      padding: 0;
      overflow: hidden;
    }

    header {
      background-size: 100%;
      display: flex;
      flex-direction: column;
      color: white;
      height: 15em;
      margin-bottom: 50px;
    }

    h1{
      font-size: 80px;
    }

    .go-back a{
      position: relative;
      top: 5px;
      display: flex;
      margin-top: 10px;
      font-size: 40px;
      padding: 20px;
    }

    .go-back:hover {
      transform: scale(1.1);
      transition: transform 0.3s ease;
    }
    .go-back:not(:hover) {
      transition: transform 0.3s ease;
    }

    .header-container{
      position: relative;
      height: 15em;
      margin-left: 50px;
      margin-top: 50px;
    }

    .btn-title{
      display: flex;
      align-items: center;
      height: 70px;
    }

    .date{
      margin-left: 130px;
      margin-top: 50px;
    }
    .article-container {
      display: flex;
      align-items: flex-start;
    }

    .content{
      margin-left: 100px;
      margin-right: 70px;
      width: 100%;
      font-family: 'Maven', sans-serif;
      letter-spacing: 2px;
      word-spacing: 4px;
      text-align: justify;
    }

    #content-box {
      flex: 1;
      margin-top: 50px;
      width: 200px;
      height: 500px;
      overflow-y: auto;
    }

    .carousel-container {
      flex: 1;
      margin-top: 50px;
      margin-right: 100px;
      width: 400px;
      height: 500px;
      position: relative;
    }

    .carousel-btn {
      position: absolute;
      top: 50%;
      transform: translateY(-50%);
      background-color: transparent;
      border: none;
      font-size: 20px;
      cursor: pointer;
      z-index: 2;
      color: #ffffff7b;
      font-size: 35px;
    }

    .carousel-btn:hover{
      color: #fffffffb;
    }

    .carousel-btn-left {
      left: 0;
    }

    .carousel-btn-right {
      right: 0;
    }

    .image-container {
      width: 100%;
      height: 100%;
    }

    {% comment %} .carousel-image {
      width: 100%;
      height: 100%;
      background-size: cover;
      background-position: center;
      border-radius: 20px;
      box-shadow: 5px 5px 15px rgba(0, 0, 0, 0.3), -5px -5px 15px rgba(255, 255, 255, 0.7);
    } {% endcomment %}

    .carousel-image {
      width: 100%;
      height: 100%;
      background-position: center;
      background-repeat: no-repeat;
      background-size: 100%;
      background-color: black;  /* ajouter une couleur de fond pour les bandes */
      border-radius: 20px;
      box-shadow: 5px 5px 15px rgba(0, 0, 0, 0.3), -5px -5px 15px rgba(255, 255, 255, 0.7);
    }


    @media screen and (max-width: 1000px) {

      html, body {
        height: 100%;
        overflow: visible;
      }

      header {
        height: 7em;
      }

      h1{
        font-size: 40px;
      }

      .go-back a{
        font-size: 12px;
      }

      .header-container {
        height: 7em;
        margin-top: 10px;
      }

      .date{
        display: flex;
        margin-left: 80px;
        margin-top: 0;
      }

      .article-container {
        display: flex;
        flex-direction: column-reverse;
        width: 100%;
        margin: auto;
      }

      .carousel-container{
        width: 630px;
        display: flex;
        flex: 1;
        justify-content: center;
        align-items: center;
        margin: auto;
      }

      .carousel-image{
        width:630px;
        height: 350px;
      }
      .image-container{
        width: 100%;
        height: 100%;
      }

      .article-container {
        display: flex;
        align-items: center;

      }

      .content{
        width: 70%;
        height: 30%;
        align-items: center;
        margin: auto;
      }

      #content-box {
        width: 70%;
        height: 50%;
        overflow: scroll;
      }
    }

  </style>
{% endblock %}

{% block content %}
    <header style="background-repeat: no-repeat; background-position: center;
      {% if post.images.all.first %}
          background-image: url('{{ post.images.all.first.img.url }}');
      {% else %}
          background-image: linear-gradient(to bottom, rgba(71, 68, 68, 0.453), rgba(0, 0, 0, 0.562));
      {% endif %}
    ">
        <div class="header-container">
          <div class="btn-title">
            <div class="go-back" style="display: inline-block; margin-right: 20px; margin-top: -10px; color:">
              <a href="javascript:void(0);" style="color: white; text-decoration: none;" onclick="window.history.back();"><i class="fa-solid fa-chevron-left fa-2xl"></i></a>
              </div>
              <h1 style="display: inline-block; text-shadow: 4px 4px 5px rgba(10, 10, 10, 0.509);">{{ post.title }}</h1>
            </div>
            <p class="date" style="text-shadow: 5px 5px 6px rgba(10, 10, 10, 0.509);">{{ post.created_on|date:'j F Y' }}</p>
        </div>
    </header>

    <article>
      <div class="article-container">
        <div class="content" id="content-box">
            {{ post.content|linebreaks|safe }}
        </div>

        <div class="carousel-container">
            <button class="carousel-btn carousel-btn-left">
                <i class="fa-solid fa-circle-chevron-left"></i>
            </button>

            <div class="image-container">
                {% for image in post.images.all %}
                  <div class="carousel-image" style="background-image: url('{{ image.img.url }}');"></div>
                {% endfor %}
            </div>

            <button class="carousel-btn carousel-btn-right">
                <i class="fa-solid fa-circle-chevron-right"></i>
            </button>
        </div>
      </div>
  </article>

    <script src="https://kit.fontawesome.com/a40355b42d.js" crossorigin="anonymous"></script>

    <script>
      document.addEventListener("DOMContentLoaded", function () {
        let currentIndex = 0;

        const imageElements = document.querySelectorAll(".carousel-image");
        const btnLeft = document.querySelector(".carousel-btn-left");
        const btnRight = document.querySelector(".carousel-btn-right");

        const imageContainers = document.querySelectorAll('.image-container .carousel-image');

      imageContainers.forEach(container => {
          const imageUrl = getComputedStyle(container).backgroundImage.slice(5, -2);
          if (imageUrl) {
              const image = new Image();
              image.src = imageUrl;
              image.onload = function() {
                  if (image.width < image.height) {  // Portrait
                      container.style.backgroundSize = 'contain';
                  } else {  // Paysage
                      container.style.backgroundSize = '100%';
                  }
              }
          }
      });
        // Initial display
        updateCarousel();

        btnLeft.addEventListener("click", function () {
            if (currentIndex > 0) {
                currentIndex--;
                updateCarousel();
            }
        });

        btnRight.addEventListener("click", function () {
            if (currentIndex < imageElements.length - 1) {
                currentIndex++;
                updateCarousel();
            }
        });

        function updateCarousel() {
            imageElements.forEach((img, index) => {
                img.style.display = index === currentIndex ? "block" : "none";
            });
        }
    });

  </script>

{% endblock %}

src/posts/templates/posts/blogpost_list.html
{% extends 'base.html' %}
{% load static %}

{% block head_extra %}
  <link rel="stylesheet" href="{% static 'css/blogpost_list.css' %}">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  <title>Journey Blog</title>
{% endblock %}

{% block content %}

  <div class="title-container">
    <div class="title">The {{ username_in_url|capfirst }}'s Journey</div>

    {% if request.user.is_authenticated and request.user.username == username_in_url %}
      <div class="post-add">
        <a href="{% url 'posts:create' %}">
          <div class="add"><i class="fa-solid fa-circle-plus"></i></div>
        </a>
      </div>
      {% endif %}
    </div>


    <div class="carousel-container">
      {% if posts %}
        <button class="carousel-btn carousel-btn-left"
          style="color: #0f34307b;"
          onmouseover="this.style.color='#0f3430fb';"
          onmouseout="this.style.color='#0f34307b';">
          <i class="fa-solid fa-circle-chevron-left fa-2xl"></i>
        </button>
      {% endif %}

      <div class="carousel-content">

        <div class="posts-grid">
          {% for post in posts %}
            {% if post.images.all.first %}
                <article id="post-{{ post.id }}" class="post-item" style="background-image: url('{{ post.images.all.first.img.url }}');">
            {% else %}
                <article id="post-{{ post.id }}" class="post-item" style="background-image: linear-gradient(to bottom, rgba(71, 68, 68, 0.453), rgba(0, 0, 0, 0.562));">
            {% endif %}
              <div class="post-info">
                  <a href="{% url 'posts:post' username=request.user.username slug=post.slug %}" class="read-article">
                    <h2><span style="font-weight: bold; color: white; text-shadow: 4px 4px 5px rgba(10, 10, 10, 0.509);">{{ post.title|capfirst }}</span></h2>
                  </a>
                    <h5><span style="text-shadow: 4px 4px 5px rgba(10, 10, 10, 0.509);">Le {{ post.created_on|date:'j F Y' }}</span></h5>
                </div>

                {% if post.author == request.user %}
                  <div class="post-actions">
                      <a href="{% url 'posts:edit' username=request.user.username slug=post.slug %}" class="edit"><span style="text-shadow: 4px 4px 5px rgba(10, 10, 10, 0.509);"><i class="fa-solid fa-pencil fa-lg"></span></i></a>
                      <a href="#" onclick="confirmDelete('{% url 'posts:delete' username=request.user.username slug=post.slug %}', '{{ post.id }}');" class="delete"><span style="text-shadow: 4px 4px 5px rgba(10, 10, 10, 0.509);"><i class="fa-regular fa-trash-can fa-lg"></span></i></a>
                    </div>
                {% endif %}
            </article>
          {% endfor %}
        </div>

      </div>
      {% if posts %}
        <button class="carousel-btn carousel-btn-right"
          style="color: #0f34307b;"
          onmouseover="this.style.color='#0f3430fb';"
          onmouseout="this.style.color='#0f34307b';">
          <i class="fa-solid fa-circle-chevron-right fa-2xl"></i>
        </button>
      {% endif %}

    </div>

    <script src="https://kit.fontawesome.com/a40355b42d.js" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
      function confirmDelete(deleteUrl, postId) {
        if (window.confirm("Êtes-vous sûr de vouloir supprimer ce post ?")) {
            $.ajax({
                url: deleteUrl,
                type: 'POST',
                headers: { 'X-CSRFToken': '{{ csrf_token }}' },
                success: function() {
                    $('#post-' + postId).remove();
                },
                error: function() {
                    alert('Il y a eu une erreur lors de la suppression du post.');
                }
            });
        }
    }
        $(document).ready(function(){
            let currentIndex = 0;

            $('.carousel-btn-right').click(function(){
                if(currentIndex < ($('.post-item').length - 3)) {
                    currentIndex++;
                    updateCarousel();
                }
            });

            $('.carousel-btn-left').click(function(){
                if(currentIndex > 0) {
                    currentIndex--;
                    updateCarousel();
                }
            });

            $('.carousel-content').on('wheel', function(e) {
              if (e.originalEvent.deltaY > 0 && currentIndex < ($('.post-item').length - 3)) { // Défilement vers la droite
                  currentIndex++;
                  updateCarousel();
              } else if (e.originalEvent.deltaY < 0 && currentIndex > 0) { // Défilement vers la gauche
                  currentIndex--;
                  updateCarousel();
              }
            });

            function updateCarousel() {
                const scrollAmount = currentIndex * 500; // 400px (largeur) + 100px (gap)
                $('.posts-grid').css('transform', 'translateX(' + -scrollAmount + 'px)');
            }
        });


    </script>

{% endblock %}