src/JourneyBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from JourneyBlog import settings
from django.conf.urls.static import static

from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")), #pour signup
    path("accounts/", include("django.contrib.auth.urls")), #pour login et logout
    path('posts/', include('posts.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/posts/urls.py
from django.urls import path
from posts.views import BlogHome, BlogPostCreate, BlogPostEdit, BlogPostDetail, BlogPostDelete, UserSearchView, SignUpView
from django.urls import path, include

# from django.views.generic.base import TemplateView

app_name = "posts"

urlpatterns = [
    path('create/', BlogPostCreate.as_view(), name="create"),
    path('search/', UserSearchView.as_view(), name="user_search"),
    path('<str:username>/', BlogHome.as_view(), name="profile"),
    path('<str:username>/<str:slug>/', BlogPostDetail.as_view(), name="post"),
    path('edit/<str:username>/<str:slug>/', BlogPostEdit.as_view(), name="edit"),
    path('delete/<str:username>/<str:slug>/', BlogPostDelete.as_view(), name="delete"),
]

src/posts/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.template.defaultfilters import slugify
from model_utils.models import TimeStampedModel

User = get_user_model()


class Pictures(TimeStampedModel):
    img = models.ImageField(upload_to='images')

    def __str__(self):
        return str(self.img)

class BlogPost(TimeStampedModel):
    title = models.CharField(max_length=255, unique=False, verbose_name="Where did you go ?")
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    last_updated = models.DateTimeField(auto_now=True)
    created_on = models.DateField(blank=True, null=True)
    published = models.BooleanField(default=False, verbose_name="Do you want to publish it ?")
    content = models.TextField(blank=True, verbose_name="Share your journey ")
    images = models.ManyToManyField(Pictures, blank=True, verbose_name="Add attachment")

    @property
    def author_or_default(self):
        return self.author.username if self.author else "L'auteur inconnu"

    # def get_absolute_url(self):
    #     return reverse("posts:home")

    class Meta:
        ordering = ['-created_on']
        verbose_name = "Article"


    def __str__(self):
      return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(f"{self.author.username}-{self.title}")
        super().save(*args, **kwargs)

src/posts/forms.py
from django import forms
from .models import Pictures
from django.forms import modelformset_factory

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


# Sign Up Form
class SignUpForm(UserCreationForm):
    # first_name = forms.CharField(max_length=30, required=False, help_text='Optional')
    # last_name = forms.CharField(max_length=30, required=False, help_text='Optional')
    email = forms.EmailField(max_length=254, help_text='Enter a valid email address')

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password1',
            'password2',
            ]

class MultipleFileInput(forms.FileInput):
    def render(self, name, value, attrs=None, renderer=None):
        if 'multiple' not in self.attrs:
            self.attrs['multiple'] = 'multiple'
        return super().render(name, value, attrs, renderer)

class PictureForm(forms.ModelForm):
    img = forms.FileField(widget=MultipleFileInput(), required=False, label='Add attachment ')

    class Meta:
        model = Pictures
        fields = ['img']

PictureFormSet = modelformset_factory(Pictures, form=PictureForm, extra=1)

src/posts/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from .forms import PictureFormSet
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.http import Http404

from django.views import View

from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from .forms import SignUpForm
from django.contrib.auth.models import User
from datetime import datetime


from posts.models import BlogPost, Pictures

User = get_user_model()


# Sign Up View
class SignUpView(CreateView):
    form_class = SignUpForm
    template_name = 'user/signup.html'

    def get_success_url(self):
        username = self.object.username
        return reverse('posts:profile', kwargs={'username': username})

class UserSearchView(View):
    def get(self, request, *args, **kwargs):
        username = request.GET.get('username')

        username = username.lower() if username else username

        # Si le nom d'utilisateur est vide ou non valide
        if not username or not self.is_valid_username(username):
            return redirect('home')

        return redirect('posts:profile', username=username.lower())

    def is_valid_username(self, username):
        return User.objects.filter(username=username).exists()

class BlogHome(ListView):
    model = BlogPost
    context_object_name = "posts"

    def get_queryset(self):
        # Obtenir le username depuis l'URL
        username = self.kwargs.get('username')
        # Obtenir le User object correspondant
        user = User.objects.get(username=username)

        try:
            # Obtenir le User object correspondant
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            raise Http404("User not found")

        # Filtrer les posts par cet utilisateur
        if self.request.user.is_authenticated and self.request.user.username == username:
            # Si l'utilisateur est authentifié et qu'il visite sa propre page, on lui montre tous ses posts
            return BlogPost.objects.filter(author=user)
        else:
            # Si un visiteur ou un autre utilisateur visite cette page, ne montrer que les posts publiés
            return BlogPost.objects.filter(author=user, published=True)

    def get_context_data(self, **kwargs):
        context = super(BlogHome, self).get_context_data(**kwargs)
        context['username_in_url'] = self.kwargs.get('username')
        return context

class BlogPostCreate(CreateView):
    model = BlogPost
    template_name = 'posts/blogpost_create.html'
    fields = ['title', 'content', 'published']

    def get_success_url(self):
        return reverse('posts:profile', kwargs={'username': self.request.user.username})

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data["pictures_formset"] = PictureFormSet(self.request.POST, self.request.FILES, prefix='pictures')
        else:
            data["pictures_formset"] = PictureFormSet(prefix='pictures')
        return data

    def form_valid(self, form):
        form.instance.author = self.request.user  # Assigner l'auteur
        form.instance.created_on = datetime.now()

        context = self.get_context_data()
        pictures_form = context["pictures_formset"][0]  # prendre le premier formulaire du formset
        self.object = form.save()

        if pictures_form.is_valid():
            for file in self.request.FILES.getlist('pictures-0-img'):
                picture = Pictures(img=file)
                picture.save()
                self.object.images.add(picture)

        return super().form_valid(form)

class BlogPostEdit(UpdateView):
    model = BlogPost
    template_name = 'posts/blogpost_edit.html'
    fields = ['title', 'content', 'published']

    def get_success_url(self):
        return reverse('posts:profile', kwargs={'username': self.request.user.username})

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data["pictures_formset"] = PictureFormSet(self.request.POST, self.request.FILES, prefix='pictures')
        else:
            data["pictures_formset"] = PictureFormSet(queryset=Pictures.objects.none(), prefix='pictures')
        return data

    def form_valid(self, form):
        form.instance.author = self.request.user  # Assigner l'auteur
        form.instance.updated_on = datetime.now()

        context = self.get_context_data()
        pictures_form = context["pictures_formset"]

        self.object = form.save()

        remove_all_images = self.request.POST.get('remove_all_images', '0') == '1'
        if remove_all_images:
            self.object.images.clear()

        if pictures_form.is_valid():
            pictures_form.instance = self.object
            pictures_form.save()

            # Supprimer les anciennes images

            for file in self.request.FILES.getlist('pictures-0-img'):
                picture = Pictures(img=file)
                picture.save()
                self.object.images.add(picture)

        return super().form_valid(form)

class BlogPostDetail(DetailView):
    model = BlogPost
    context_object_name = "post"



class BlogPostDelete(DeleteView):
    model = BlogPost
    success_url = reverse_lazy("posts:profile")
    def get_success_url(self):
        return reverse('posts:profile', kwargs={'username': self.request.user.username})

src/posts/templates/base.html
{% load static %}

<html lang="fr">

{% block head_extra %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">

    {% block title %}{% endblock %}
</head>
{% endblock %}

<body>

{% block nav %}
  {% if request.user.is_authenticated %}

    <nav class="auth-nav">

      <div class="profile">
        <a href="{% url 'posts:profile' request.user.username %}"><button class="btn-profile"><i class="fa-solid fa-user-astronaut fa-3x"></i></button></a>
      </div>

      <div class="search-bar">
        <form action="{% url 'posts:user_search' %}" method="get">
          <input type="text" name="username" placeholder="Search by username">
          <button class="search-btn" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
        </form>
      </div>

      <div class="logout">
        <a href="{% url 'logout' %}"><button class="btn-logout">Logout</button></a>
      </div>
    </nav>
  {% endif %}
{% endblock %}

<section id="blog">
    {% block content %}{% endblock %}
</section>
<script src="https://kit.fontawesome.com/a40355b42d.js" crossorigin="anonymous"></script>

</body>
</html>

src/posts/templates/blogpost_base.html
<html lang="fr">

{% block head_extra %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %}{% endblock %}
</head>
{% endblock %}

<body>

    {% block content %}{% endblock %}

</body>
</html>

src/posts/templates/home.html
{% extends 'home_base.html' %}
{% load static %}

{% block head_extra %}
  <link rel="stylesheet" href="{% static 'css/home.css' %}">

  {% if request.user.is_authenticated %}
    <nav class="auth-nav">
      <ul>
        <li><a href="{% url 'posts:profile' request.user.username %}"><button class="btn-profile"><i class="fa-solid fa-user-astronaut fa-3x"></i></button></a></li>
        <li><a href="{% url 'logout' %}"><button class="btn-logout">Logout</button></a></li>
      </ul>
    </nav>
    {% else %}
    <nav class="non-auth-nav">
      <ul>
        <li><a href="{% url 'login' %}"><button class="btn-login">Login</button></a></li>
        <li><a href="{% url 'signup' %}"><button class="btn-signup">Sign Up</button></a></li>
      </ul>
    </nav>
    {% endif %}

  {% block title %}
    <div class="catchy-words">
      <div class="h1">Travel, Enjoy & Share</div>
    </div>
  {% endblock %}
{% endblock %}


{% block content %}
<div class="center-container">
    <div class="background-container" >
      <img src="{% static 'images/iceland1.webp' %}" alt="Iceland Image">
    </div>

    <div class="search-bar">
      <form action="{% url 'posts:user_search' %}" method="get">
        <div class="input-btn">
          <input type="text" name="username" placeholder="Search by username">
          <button class="search-btn" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
        </div>
      </form>
    </div>
  </div>

{% endblock %}

src/posts/templates/home_base.html
{% load livereload_tags %}
<html lang="fr">

{% block head_extra %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %}{% endblock %}

</head>
{% endblock %}
<body>

<section id="home">
    {% block content %}{% endblock %}

</section>
<script src="https://kit.fontawesome.com/a40355b42d.js" crossorigin="anonymous"></script>
</body>
</html>